### ISSUE TITLE
Ensure correct ordering of overwritten properties

### ISSUE THREAD

**Issue by Perni1984** [apiaryio/attributes-kit#212] opened 2016-02-25 11:10 UTC
When I put the following MSON in attributes-kit, the ordering of the overwritten `city` property is wrong. It is put on the last position of the `Testcompany` but should be in the middle after `zip`.

	# Data Structures

	## Testcompany (Company)
	- city: test

	## Company (object)
	- name: Jane Doe GmbH (string, required)
	- street:  South Street 20 (string, required)
	- zip: 90000 (string, required)
	- city: Sunshine (string, required)
	- country: USA (string, required)
	- description: Personal Trainer (string)
	- email: jane.doe@email.com (string)
	- tel: 123456763 (string)
	- tel_code: 0043 (string)
	- url: http://www.offisy.at (string)

Wrong:
![image](https://cloud.githubusercontent.com/assets/9039956/13318026/b8957746-dbb8-11e5-98a8-d6726b6ca5e7.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/9039956/13317982/781c7b74-dbb8-11e5-9a50-567eb07be157.png)

**Comment by Baggz** [comment] 2016-02-25 11:13
Ah, thanks, @Perni1984, for reporting!

It might be related to the way we handle inheritance (and references in general). @danielgtaylor, do you think you can have a look whether the issue isn't in Eidolon package?

**Comment by Perni1984** [comment] 2016-02-25 11:55
@Baggz: thanks for reacting so quickly. I am currently writing a documentation for a Json-api compatible api in api-blueprint and this bug is extremely annoying.

**Comment by danielgtaylor** [comment] 2016-02-25 19:53
@Perni1984 this is definitely due to the dereferencing done in [Eidolon](https://github.com/danielgtaylor/eidolon). The current algorithm adds items in order, then removes duplicates by leaving the last added duplicate item, which is why you see `city` moved to the end. I'll see about using a swap algorithm instead so the items stay in-place. Thanks for reporting this issue!

**Comment by danielgtaylor** [comment] 2016-02-25 23:39
I've opened a pull request (linked above this post ^) that should hopefully fix the issue for you once it gets reviewed, merged, and released.

**Comment by Perni1984** [comment] 2016-02-26 06:48
@danielgtaylor: thanks for tackling this issue so quickly.

**Closed** 2016-02-26 07:47 UTC

**Comment by Baggz** [comment] 2016-02-26 08:31
@Perni1984 

```Bash
+ attributes-kit@0.13.1
```

New version of the Attributes Kit has been released and published to NPM! :rocket: Updated version of the Attributes Kit will be available in Apiary later today (26 Feb 2016, CET).

**Comment by Perni1984** [comment] 2016-02-26 09:00
wow, that's fast! Great support! Thanks.

**Comment by Baggz** [comment] 2016-02-26 10:10
Just a note—Attributes Kit 0.13.1 has been deployed to Apiary.

**Comment by Perni1984** [comment] 2016-02-26 10:12
works like a charm.

**Comment by Baggz** [comment] 2016-02-26 10:25
Great to hear that, @Perni1984! Thanks a lot for your report! If you find more issues in the MSON rendering, please let us know.

Thanks again and have an awesome Friday!
